# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccc < Formula
  desc "CLI tool for managing zmx sessions on remote machines over SSH"
  homepage "https://github.com/mark-jaeger/ccc"
  version "2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.0/ccc_2.0_darwin_amd64.tar.gz"
      sha256 "11952623c5e1a8bffaf12f2dd98c9dc8b2ad9f37952a454b4ee0fd8703ca1a09"

      define_method(:install) do
        bin.install "ccc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.0/ccc_2.0_darwin_arm64.tar.gz"
      sha256 "a18a250019c0c7c86b76351eea48873e3206ffedf1e026275454c7801e883f4e"

      define_method(:install) do
        bin.install "ccc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.0/ccc_2.0_linux_amd64.tar.gz"
      sha256 "0d1fae28fa46b03ff2789efd1ca3c6ee261786cdcb004f7a211a6921df92c4c6"
      define_method(:install) do
        bin.install "ccc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.0/ccc_2.0_linux_arm64.tar.gz"
      sha256 "12f79d80d762388c7c5577cb1568671e53a34a9b47f00f8f9b37dfe85425f703"
      define_method(:install) do
        bin.install "ccc"
      end
    end
  end

  test do
    system "#{bin}/ccc", "--version"
  end
end
