# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccc < Formula
  desc "CLI tool for managing zmx sessions on remote machines over SSH"
  homepage "https://github.com/mark-jaeger/ccc"
  version "2.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.1.2/ccc_2.1.2_darwin_amd64.tar.gz"
      sha256 "3d1045db607fb3544226686cbcc25441daad3721919f40e09828443e02f00d5d"

      define_method(:install) do
        bin.install "ccc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.1.2/ccc_2.1.2_darwin_arm64.tar.gz"
      sha256 "3ce43517d1623b03b881aaa0c23a4a1bf2d4323e6a67cf197f1772906facdff3"

      define_method(:install) do
        bin.install "ccc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.1.2/ccc_2.1.2_linux_amd64.tar.gz"
      sha256 "dca2766ce0c028f4db705426829dea4983a30f0640982767cea045d0af877145"
      define_method(:install) do
        bin.install "ccc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mark-jaeger/ccc/releases/download/v2.1.2/ccc_2.1.2_linux_arm64.tar.gz"
      sha256 "e71deaef72a78472e455d7d87a3d0e47a601896ac4fc483214d89dec68efc2b4"
      define_method(:install) do
        bin.install "ccc"
      end
    end
  end

  test do
    system "#{bin}/ccc", "--version"
  end
end
