# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccc" do
  name "ccc"
  desc "CLI tool for managing tmux sessions on remote machines over SSH"
  homepage "https://github.com/mark-jaeger/ccc"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccc"

  on_macos do
    on_intel do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_darwin_amd64.tar.gz"
      sha256 "b6cd6b34906a07b3e6f05c6d4681b3cdf7cdcf3f14b91f5c9f85e634b5e35215"
    end
    on_arm do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_darwin_arm64.tar.gz"
      sha256 "7608acf2b91f61d31ea8a13ee7697f7fde700a5d3f2b14c99c4c9b154b4550fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_linux_amd64.tar.gz"
      sha256 "2d45ec60fe4c8ae5913d71f6d8f0ff96ea45d584aebdaaa35dfd87f161197520"
    end
    on_arm do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_linux_arm64.tar.gz"
      sha256 "c4e61c1683ec8bc46b4e53480acef007bc29ce89c158c7aa6caf359bec014fac"
    end
  end

  # No zap stanza required
end
