# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccc" do
  name "ccc"
  desc "CLI tool for managing tmux sessions on remote machines over SSH"
  homepage "https://github.com/mark-jaeger/ccc"
  version "0.1.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccc"

  on_macos do
    on_intel do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_darwin_amd64.tar.gz"
      sha256 "f7a2bc944fe9dd6ba4b899f0c372c031c722e478da55f5b90285123541e527c9"
    end
    on_arm do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_darwin_arm64.tar.gz"
      sha256 "e880915dbb518541fe03a88dd81326c7ce8ebc1a4b37d46a7e3c06f53b05357a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_linux_amd64.tar.gz"
      sha256 "361d5eab02f03edada94e5c5a08125e69eed9b5c596dcfebcbfd9915c3e35840"
    end
    on_arm do
      url "https://github.com/mark-jaeger/ccc/releases/download/v#{version}/ccc_#{version}_linux_arm64.tar.gz"
      sha256 "071a4dc8e6b2ddfdd86896f90b5ad4820207a5cff9e79f2e2a537ca80cfb4da8"
    end
  end

  # No zap stanza required
end
